apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appname }}
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: flask
  selector:
    app: {{ .Values.appname }}
    tier: frontend
  type: LoadBalancer